apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: jagritnokwal
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30000    # permanent host port for HTTP
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443   # optional for HTTPS
